### PR TITLE
DeepL accepts "auto", no need for additional libraries.

### PR DESCRIPTION
**Pull request by egeakman**

### CODE REVIEW

**Comment by missuo** [comment]
I've checked your code and you've completely removed the possibility of human input of the source language, which obviously doesn't make sense, and automated detection isn't necessarily 100% accurate. Of course, if the user doesn't specify the source language, for what you're saying about not using Python's packages to detect it and leaving it to DeepL to detect the language, that's fine with me.

Translated with DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation

**Comment by missuo** [comment]
I've checked your code and you've completely removed the possibility of human input of the source language, which obviously doesn't make sense, and automated detection isn't necessarily 100% accurate. Of course, if the user doesn't specify the source language, for what you're saying about not using Python's packages to detect it and leaving it to DeepL to detect the language, that's fine with me.

**Comment by egeakman** [comment]
I'm not removing human input by any means, I'm adding a assigning a default value to the language parameters.

Please see:

- https://docs.python.org/3/tutorial/controlflow.html#default-argument-values
- https://www.geeksforgeeks.org/default-arguments-in-python/

**Comment by missuo** [comment]
make sense, have you tested the code?

**Comment by egeakman** [comment]
Yes, it works.

**Comment by missuo** [comment]
Thanks

**Pull request merged**
